### ISSUE TITLE
rubocop-faker can not find offenses in factorybot models.

### ISSUE THREAD

**Issue by GoktugOzturk** [koic/rubocop-faker#2] opened 2019-12-10 20:17 UTC
When I run the command to upgrade deprecated usages, it found and fixed deprecated code on controller specs. 
But we're also using faker to generate random data for factorybot models. It doesn't find those usages and cannot fix them.

Here is an example of factorybot model.

./spec/factories/component.rb
```FactoryBot.define do
  factory :component do
    event
    type_id { Faker::Number.between(from: 1, to: 11) }
    custom_name { Faker::Name.name }
    custom_picture { Faker::Placeholdit.image }
    order_value { Faker::Number.number(1) }
    is_hidden { false }
    classification { Faker::Number.number(4) }
  end
end
```

**Comment by koic** [comment] 2019-12-12 07:03
I cannot reproduce this issue when using rubocop-faker 0.2.0.

```console
% gem query -ln rubocop-faker

*** LOCAL GEMS ***

rubocop-faker (0.2.0)

% cat example.rb
Faker::Number.number(1)

% ruby -rfaker example.rb
example.rb:1: Passing `digits` with the 1st argument of `number` is deprecated. Use keyword argument like `number(digits: ...)` instead.

To automatically update from positional arguments to keyword arguments,
install rubocop-faker and run:

rubocop \
  --require rubocop-faker \
  --only Faker/DeprecatedArguments \
  --auto-correct

% rubocop \
>   --require rubocop-faker \
>   --only Faker/DeprecatedArguments \
>   --auto-correct
Inspecting 1 file
C

Offenses:

example.rb:1:22: C: [Corrected] Faker/DeprecatedArguments: Passing 1 with the 1st argument of Faker::Number.number is deprecated. Use keyword argument like Faker::Number.number(digits: 1) instead.
Faker::Number.number(1)
                     ^

1 file inspected, 1 offense detected, 1 offense corrected

% cat example.rb
Faker::Number.number(digits: 1)
```

Could you show me the steps to reproduce the issue using rubocop-faker 0.2.0?

**Comment by koic** [comment] 2019-12-19 03:00
I will close this issue. If the issue reappears, please reopen the issue with the reproduction steps. Thank you.

**Closed as completed by koic** 2019-12-19 03:00 UTC

**Comment by chamnap** [comment] 2020-02-08 10:36
@GoktugOzturk, In my case, I need to temporary remove my exclude `- 'spec/**/*'` on `.rubocop.yml` first before running the command.
