### ISSUE TITLE
rubocop --require rubocop-faker does not find file

### ISSUE THREAD

**Issue by mjy** [koic/rubocop-faker#1] opened 2019-10-31 19:24 UTC
When I use

`rubocop --require rubocop-faker --only Faker/DeprecatedArguments --auto-correct`

then I get 

```
cannot load such file -- rubocop-faker
```

ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

```
*** LOCAL GEMS ***

rubocop (0.76.0)
rubocop-faker (0.2.0)
rubocop-rails (2.3.2)
rubocop-require_tools (0.1.2)
rubocop-rspec (1.36.0)
```

**Comment by koic** [comment] 2019-11-03 03:34
I cannot reproduce the issue.

```console
% ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin17]

% gem i rubocop-faker
Successfully installed rubocop-faker-0.2.0
1 gem installed

% rubocop --require rubocop-faker --only Faker/DeprecatedArguments --auto-correct
Inspecting 1 file
.

1 file inspected, no offenses detected
```

Could you try `% gem i rubocop-faker` before running `rubocop` command?

**Comment by koic** [comment] 2019-11-08 16:35
I will close the issue. If this doesn't solve it, feel free to reopen the issue.

**Closed as completed by koic** 2019-11-08 16:35 UTC

**Comment by mjy** [comment] 2019-11-08 17:05
Thanks for feedback, sorry for confusion.  Both 2.6.5 and 2.6.3 are working for me now, not sure what I missed prior.

**Comment by antarr** [comment] 2023-04-07 19:41
I've been running into this as well with 2.7.7
